name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Run Unit Tests
      run: bash ./gradlew test --stacktrace 
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew assembleDebug
      
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
      with:
        appId: '1:521644696500:android:a021b3132a70c4636e48e1'
        token: '1//0geuNhTLIxJbiCgYIARAAGBASNwF-L9IrPdw-OYX222swE85aBVPpAMctAlXZlAJm0k-1YwrUtZF8Etpzh3dedfVN1UlHWSqRzaA'
        groups: testers
        file: app/build/outputs/apk/debug/app-debug.apk
    
    
