name: unit test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  UnitTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Run Unit Tests
      run: bash ./gradlew test
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.0.0-beta.2
      if: always()
      with:
        files: test-results/**/*.xml
