name: unit test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  UnitTest:

    runs-on: ubuntu-latest

    steps:
    - name: Run Unit Tests
      run: bash ./gradlew app:testDebug --tests=com.skripsi.andra.ExampleUnitTest
